# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=512, verbose_name='Идентификатор')),
                ('username', models.CharField(max_length=512, verbose_name='Имя пользователя')),
                ('computername', models.CharField(max_length=512, verbose_name='Имя компьютера')),
                ('eventtime', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'db_table': 'usb_journal',
                'verbose_name_plural': 'Журнал событий',
                'verbose_name': 'Журнал событий',
            },
        ),
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=512, verbose_name='Идентификатор')),
            ],
            options={
                'db_table': 'usb_list',
                'verbose_name_plural': 'Список зарегистрированных USB-устройств',
                'verbose_name': 'Список зарегистрированных USB-устройств',
            },
        ),
    ]
